DROP TABLE Kocury CASCADE CONSTRAINTS PURGE;
DROP TABLE Funkcje CASCADE CONSTRAINTS PURGE;
DROP TABLE Wrogowie_kocurow CASCADE CONSTRAINTS PURGE;
DROP TABLE Wrogowie CASCADE CONSTRAINTS PURGE;
DROP TABLE Bandy CASCADE CONSTRAINTS PURGE;
